repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml", "--ignore-missing-imports"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: python
        additional_dependencies: ["pytest>=8.4.2", "numpy>=2.3.0"]
        pass_filenames: false
        types: [python]
