from src.pycfd_types import Array as Array, IDir as IDir
from src.states import State as State, get_state_from_array as get_state_from_array, set_state_into_array as set_state_into_array
from src.varindexes import IBX as IBX, IBY as IBY, IU as IU, IV as IV

def fillAbsorbing(Q: Array, iref: int, jref: int, idir: IDir) -> State: ...
def fillReflecting(Q: Array, i: int, j: int, iref: int, jref: int, idir: IDir) -> State: ...
def fillPeriodic(Q: Array, i: int, j: int, idir: IDir) -> State: ...
def fillBoundaries(Q: Array) -> None: ...
