from typing import Iterable

problem_name: str
MHD: bool
gamma: float
Nfields: int
Nx: int
Ny: int
Nghosts: int
Ntx: int
Nty: int
ibeg: int
iend: int
jbeg: int
jend: int
ParallelRange: Iterable[int]
range_tot: Iterable[int]
range_dom: Iterable[int]
range_xbound: Iterable[int]
range_ybound: Iterable[int]
range_slopes: Iterable[int]
xmax: float
xmin: float
ymax: float
ymin: float
dx: float
dy: float
boundary_x: str
boundary_y: str
tend: float
CFL: float
reconstruction: str
time_stepping: str
riemann_solver: str
epsilon: float
smallr: float
log_frequency: int
save_freq: float
