from src.pycfd_types import Array as Array, IDir as IDir, real_t as real_t
from src.varindexes import IBX as IBX, IBY as IBY, IBZ as IBZ, IP as IP, IPSI as IPSI, IR as IR, IU as IU, IV as IV, IW as IW
from typing import Callable

def get_pos(i: int, j: int) -> tuple[real_t, real_t]: ...
def init_sod_x(Q: Array, i: int, j: int) -> None: ...
def init_orszag_tang(Q: Array, i: int, j: int) -> None: ...
def init_test(Q: Array, i: int, j: int) -> None: ...

problems: dict[str, Callable[..., None]]

def init_problem(Q: Array, problem_name: str) -> None: ...
