from src.physics import speed_of_sound as speed_of_sound
from src.pycfd_types import Array as Array, IDir as IDir, real_t as real_t
from src.states import State as State, primToCons as primToCons
from src.varindexes import IBX as IBX, IBY as IBY, IBZ as IBZ, IE as IE, IP as IP, IR as IR, IU as IU, IV as IV, IW as IW

def logMean(a: float, b: float) -> float: ...
def computeFlux(q: State) -> State: ...
def hll(qL: State, qR: State) -> State: ...
def fivewaves(qL: State, qR: State) -> State: ...
def riemann(qL: State, qR: State) -> State: ...
