from src.boundaries import fillBoundaries as fillBoundaries
from src.pycfd_types import Array as Array, IDir as IDir, real_t as real_t
from src.riemann import riemann as riemann
from src.states import State as State, consToPrim as consToPrim, get_state_from_array as get_state_from_array, set_state_into_array as set_state_into_array, swap_components as swap_components
from src.varindexes import IBX as IBX, IBY as IBY, IBZ as IBZ, IPSI as IPSI, IR as IR, IU as IU, IV as IV, IW as IW

def reconstruct(Q: Array, slopes: Array, i: int, j: int, sign: real_t, idir: IDir) -> State: ...
def minmod(dL: real_t, dR: real_t) -> real_t: ...

slopesX: Array
slopesY: Array

def compute_slopes(Q: Array) -> None: ...
def compute_fluxes_and_update(Q: Array, Unew: Array, dt: real_t) -> None: ...
def euler_step(Q: Array, Unew: Array, dt: real_t) -> None: ...
def update(Q: Array, Unew: Array, dt: real_t) -> None: ...
