name: Lint & Typecheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Typecheck on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks (all files)
        run: pre-commit run --all-files || true
      - name: Run flake8
        run: flake8
      - name: Run mypy
        run: mypy src --ignore-missing-imports
